### ISSUE TITLE
Code showing error when creating FlowsheetBlock!

### ISSUE THREAD

**Issue by Eloraafrin1994** [watertap-org/watertap#1393] opened 2024-05-18 17:52 UTC
### Description

The code fails while running watertap test-suite and tutorial code. It fails in 
**m.fs = FlowsheetBlock(dynamic=False)**

It gives the same error in Windows and Linux. Full error snippet
sadun@sadun-MS-7C83:~/water-tap-stuffs$ pytest --pyargs watertap
=========================================================================================== test session starts ===========================================================================================
platform linux -- Python 3.8.19, pytest-8.2.0, pluggy-1.5.0
rootdir: /home/sadun/water-tap-stuffs
collected 3172 items / 1 error                                                                                                                                                                            

================================================================================================= ERRORS ==================================================================================================
_____________________________________________________________________ ERROR collecting property_models/tests/test_cryst_prop_pack.py ______________________________________________________________________
../.conda/envs/watertap/lib/python3.8/site-packages/watertap/property_models/tests/test_cryst_prop_pack.py:37: in <module>
    class TestDefaultNaClwaterProperty:
../.conda/envs/watertap/lib/python3.8/site-packages/watertap/property_models/tests/test_cryst_prop_pack.py:41: in TestDefaultNaClwaterProperty
    m.fs = FlowsheetBlock(dynamic=False)
../.conda/envs/watertap/lib/python3.8/site-packages/idaes/core/base/process_block.py:165: in __new__
    n = _ScalarProcessBlockMeta(bname, (cls._ComponentDataClass, cls), {})
../.conda/envs/watertap/lib/python3.8/site-packages/idaes/core/base/process_block.py:133: in __new__
    return type.__new__(mcs, name, bases, dct)
E   TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
============================================================================================ warnings summary =============================================================================================
../.conda/envs/watertap/lib/python3.8/site-packages/pydantic/_internal/_fields.py:160
  /home/sadun/.conda/envs/watertap/lib/python3.8/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_objects" has conflict with protected namespace "model_".
 
  You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
    warnings.warn(

../.conda/envs/watertap/lib/python3.8/site-packages/pydantic/main.py:1115: 210 warnings
  /home/sadun/.conda/envs/watertap/lib/python3.8/site-packages/pydantic/main.py:1115: PydanticDeprecatedSince20: The `parse_obj` method is deprecated; use `model_validate` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.7/migration/
    warnings.warn(

../.conda/envs/watertap/lib/python3.8/site-packages/watertap/unit_models/tests/test_cstr.py:265
  /home/sadun/.conda/envs/watertap/lib/python3.8/site-packages/watertap/unit_models/tests/test_cstr.py:265: PytestUnknownMarkWarning: Unknown pytest.mark.ui - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.ui

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================================================================= short test summary info =========================================================================================
ERROR property_models/tests/test_cryst_prop_pack.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
===================================================================================== 212 warnings, 1 error in 10.93s =====================================================================================

### Expected Behavior

The test suite is supposed to return 0 Errors.

### Steps to Reproduce

1.  Follow the installation instructions in github docs
2.  Run the test suite
3.  Get Error

### Environment

- OS: Ubuntu 20.04 LTS / Windows 10.0
- Python: 3.8
- WaterTAP: 0.12

**Comment by lbianchi-lbl** [comment] 2024-05-19 19:43
Hi @Eloraafrin1994, thanks for reporting this.

The cause of this is a known incompatibility between Pyomo 6.7.2 and IDAES 2.4.0, and therefore also affects WaterTAP which depends on both (#1382). This has already been fixed in IDAES, but has not yet made its way into a release. To resolve the issue in the meantime, you can install WaterTAP from the `main` branch of this repository.

To do so, after activating the `watertap` Conda env, run:

```sh
pip install "git+https://github.com/watertap-org/watertap@main"
```

Let me know if this doesn't solve the issue.

**Closed as completed** 2024-06-20 21:00 UTC
Labels: bug, Priority:Normal
