### ISSUE TITLE
Installing watertap-dev on Mac OS 10.15.7

### ISSUE THREAD

**Issue by kurbansitterley** [watertap-org/watertap#267] opened 2021-11-24 19:30 UTC
I am installing the ``watertap-dev`` environment on my Mac following the instructions on readthedocs and the onboarding slides:

- ``conda create --name watertap-dev --yes python=3.8 pip=21.1 && conda activate watertap-dev``
- ``pip install -r requirements-dev.txt``

Initial attempt at running tutorial resulted in:

- ``ApplicationError: No executable found for solver 'ipopt'``

I deleted that environment and installed and repeated the install instructions above but added 

- ``idaes get-extensions`` 

I knew from watertap3 environments that that command isn't supported for Mac, but I did *not* get the ``Exception: Mac OSX currently unsupported`` error I get when trying ``idaes get-extensions`` in my watertap3 environment. Instead, I got:

- ``Exception: lib binaries are unavailable for darwin``

So I installed ipopt with:

- ``conda install -c conda-forge ipopt``

And I am able to run the tutorial. However, when running ``pytest``, it fails 30 tests. 

The traceback for the ``idaes get-extensions`` error and error report are here: 
[watertap_mac_install_error.txt](https://github.com/watertap-org/watertap/files/7598280/watertap_mac_install_error.txt)
 
This is way outside my realm of knowledge so looking to @ksbeattie @lbianchi-lbl @bknueven @andrewlee94

**Comment by lbianchi-lbl** [comment] 2021-11-29 18:13
Hi @kurbansitterley, thanks for the report and detailed information. As far as my very limited understanding goes, macOS support for IDAES is still being worked on and not yet available. Could you provide a bit more detail on the expected behavior of the setup you tried (e.g., particular steps or cases where you'd expect it to run successfully on macOS)?

From the error messages in the failing tests, it looks like the issues might be related to the solver and/or binary/library dependencies (`RuntimeError: Cannot load the PyNumero ASL interface (pynumero_ASL)`).

**Comment by bknueven** [comment] 2021-11-30 00:36
Can you try:
```
conda install cmake
pyomo build-extensions
```
You should see something at the end like:
```
Installed PyNumero libraries to /Users/bknueven/.pyomo/lib
INFO: Finished building Pyomo extensions.
INFO: The following extensions were built:
        [FAIL]  appsi
        [FAIL]  mcpp
        [ OK ]  pynumero
```
This should resolve the `RuntimeError` @lbianchi-lbl pointed out. You may also need to install `clang` by grabbing the macOS developer tools, if you haven't already.

With these changes, I get only 8 test failures with conda-forge Ipopt version 3.14.4 on Pyomo main / IDAES main on my Mac. The `appsi` and `mcpp` failures are okay.


In the next few days I'm going to try to create a conda-only workflow for compiling Ipopt with HSL on macOS, which will hopefully resolve the remaining issues.

**Comment by bknueven** [comment] 2021-11-30 21:00
Related to IDAES/idaes-ext/issues/69. We should maybe try the instructions [here as well](https://github.com/IDAES/idaes-ext/blob/adowling2-macos/macOS_notes.md).

**Comment by kurbansitterley** [comment] 2021-12-01 18:46
@lbianchi-lbl this was me setting up the environment via the tutorial/onboarding materials, so I had no expectations from a modeling perspective. 

I did
```
conda install cmake
pyomo build-extensions
```
And did indeed see what @bknueven mentioned:
```
Installed PyNumero libraries to /Users/ksitterl/.pyomo/lib
INFO: Finished building Pyomo extensions.
INFO: The following extensions were built:
        [FAIL]  mcpp
        [FAIL]  appsi
        [ OK ]  pynumero
```

Running ``pytest`` failed 12 tests for me. I don't see the *same* ``RunTimeError`` but do have ``RuntimeError: The solver failed to converge to an optimal solution`` in the error report (summary attached). I have ipopt 3.14.4.

[watertap-dev_pytest_report_dec1.txt](https://github.com/watertap-org/watertap/files/7636457/watertap-dev_pytest_report_dec1.txt)

**Comment by bknueven** [comment] 2021-12-01 20:14
@kurbansitterley this is actually a good result, all things considered. The version of Ipopt that comes with conda uses a different linear algebra library than the one that ships with IDAES, and the only tests that fail are a single chemistry test and the 1DRO tests.

I'm wondering if we can get those working with MUMPS Ipopt, and shouldn't just test against it...

**Comment by ksbeattie** [comment] 2021-12-02 21:20
The real fix here is to get MacOS support in IDAES's get-extentions...

**Comment by ksbeattie** [comment] 2022-02-03 21:24
@kurbansitterley is it ok to close this issue now?  If so, please do.

**Closed as completed** 2022-02-04 16:58 UTC
Labels: Priority:High
